language: ruby
rvm:
  - 2.2.3
before_install:
  - rvm install 2.2.3
install:
  - bundle install --path vendor/bundle
script:
  - bundle exec middleman build
  - bundle exec middleman deploy
branches:
  only:
  - master
